// Code generated by gen from kernel_i64_neon.go; DO NOT EDIT.

//go:build goexperiment.simd && arm64

package vqsort

import (
	"math/bits"
	"simd/archsimd"
)

// maskBitsF64 reduces a 2-lane comparison mask to a 2-bit index.
//
// There is no ReduceSum for 64-bit elements on arm64 and no ToBits on any arm64
// mask, so the mask vector is read out one lane at a time. Each lane is all
// ones or all zeros, so the low bit carries the answer. Two independent UMOVs
// are cheaper here than manufacturing a 32-bit mask to reduce.
func maskBitsF64(m archsimd.Mask64x2) int {
	b := m.ToInt64x2().ToBits()
	return int(b.GetElem(0)&1) | int(b.GetElem(1)&1)<<1
}

func partitionVecF64(v, pivot archsimd.Float64x2) (archsimd.Float64x2, int) {
	m := maskBitsF64(pivot.Less(v))
	idx := archsimd.LoadUint8x16Array(&permTable64x2[m])
	lr := v.ToBits().ReshapeToUint8s().LookupOrZero(idx).ReshapeToUint64s().BitsToFloat64()
	return lr, lanes64 - bits.OnesCount(uint(m))
}

func storeBothF64(keys []float64, wl, wr int, v archsimd.Float64x2) {
	v.StoreArray((*[lanes64]float64)(at(keys, wl, lanes64)))
	v.StoreArray((*[lanes64]float64)(at(keys, wr-lanes64, lanes64)))
}

func storeOneF64(keys []float64, wl, wr int, pivot, v archsimd.Float64x2) (int, int) {
	p, n := partitionVecF64(v, pivot)
	storeBothF64(keys, wl, wr, p)
	return wl + n, wr - (lanes64 - n)
}

// storeLastF64 places the drain's final vector by exact copy; see storeLastI32
// for why the paired stores cannot be used there.
func storeLastF64(keys []float64, wl, wr int, pivot, v archsimd.Float64x2) (int, int) {
	p, n := partitionVecF64(v, pivot)
	var packed [lanes64]float64
	p.StoreArray(&packed)
	copy(keys[wl:wl+n], packed[:n])
	copy(keys[wr-(lanes64-n):wr], packed[n:])
	return wl + n, wr - (lanes64 - n)
}

func storeFourF64(keys []float64, wl, wr int, pivot, v0, v1, v2, v3 archsimd.Float64x2) (int, int) {
	p0, n0 := partitionVecF64(v0, pivot)
	p1, n1 := partitionVecF64(v1, pivot)
	p2, n2 := partitionVecF64(v2, pivot)
	p3, n3 := partitionVecF64(v3, pivot)

	storeBothF64(keys, wl, wr, p0)
	wl, wr = wl+n0, wr-(lanes64-n0)
	storeBothF64(keys, wl, wr, p1)
	wl, wr = wl+n1, wr-(lanes64-n1)
	storeBothF64(keys, wl, wr, p2)
	wl, wr = wl+n2, wr-(lanes64-n2)
	storeBothF64(keys, wl, wr, p3)
	return wl + n3, wr - (lanes64 - n3)
}

func loadFourF64(keys []float64, i int) (a, b, c, d archsimd.Float64x2) {
	p := (*[unroll64]float64)(at(keys, i, unroll64))
	return archsimd.LoadFloat64x2Array((*[lanes64]float64)(p[0:lanes64])),
		archsimd.LoadFloat64x2Array((*[lanes64]float64)(p[lanes64 : 2*lanes64])),
		archsimd.LoadFloat64x2Array((*[lanes64]float64)(p[2*lanes64 : 3*lanes64])),
		archsimd.LoadFloat64x2Array((*[lanes64]float64)(p[3*lanes64 : 4*lanes64]))
}

func partitionRemainderF64(keys []float64, pivot float64, buf []float64) (wl, nBuf int) {
	for _, k := range keys {
		right := 0
		if k > pivot {
			right = 1
		}
		keys[wl] = k
		buf[nBuf] = k
		wl += 1 - right
		nBuf += right
	}
	return wl, nBuf
}

// partitionF64 is partitionI32 at two lanes; the capacity invariants are stated
// there and hold for any lane count, since they depend only on the unroll
// factor being four vectors.
func partitionF64(keys []float64, pivot float64, pv archsimd.Float64x2, buf *[bufLen64]float64) int {
	n := len(keys)
	rem := n % unroll64
	wl, nBuf := partitionRemainderF64(keys[:rem], pivot, buf[:])
	readL, readR, wr := rem, n, n

	l0, l1, l2, l3 := loadFourF64(keys, readL)
	readL += unroll64
	readR -= unroll64
	r0, r1, r2, r3 := loadFourF64(keys, readR)

	for readL < readR {
		var v0, v1, v2, v3 archsimd.Float64x2
		if wr-readR < readL-wl {
			readR -= unroll64
			v0, v1, v2, v3 = loadFourF64(keys, readR)
		} else {
			v0, v1, v2, v3 = loadFourF64(keys, readL)
			readL += unroll64
		}
		wl, wr = storeFourF64(keys, wl, wr, pv, v0, v1, v2, v3)
	}

	wl, wr = storeFourF64(keys, wl, wr, pv, l0, l1, l2, l3)
	wl, wr = storeOneF64(keys, wl, wr, pv, r0)
	wl, wr = storeOneF64(keys, wl, wr, pv, r1)
	wl, wr = storeOneF64(keys, wl, wr, pv, r2)
	wl, wr = storeLastF64(keys, wl, wr, pv, r3)

	copy(keys[wl:wr], buf[:nBuf])
	return wl
}

// sortBaseF64 sorts a range small enough to need no partitioning; see
// sortBaseI32 for why the network is used above a handful of keys.
func sortBaseF64(s []float64) {
	n := len(s)
	if n <= insertionFloor64 {
		insertionSort(s)
		return
	}
	var buf [networkKeys64]float64
	copy(buf[:], s)
	for i := n; i < networkKeys64; i++ {
		buf[i] = padF64
	}
	sortNetworkF64(&buf)
	copy(s, buf[:n])
}

// minMaxF64 is scalar: arm64 has no 64-bit integer Min or Max, and this runs
// only on the degenerate path where a partition put every key on the left.
func minMaxF64(s []float64) (float64, float64) {
	lo, hi := s[0], s[0]
	for _, v := range s[1:] {
		if v < lo {
			lo = v
		}
		if v > hi {
			hi = v
		}
	}
	return lo, hi
}

func choosePivotF64(s []float64, rng *sfc64) float64 {
	n := uint32(len(s))
	if len(s) < nintherFloor {
		return medianOf3(s[rng.bounded(n)], s[rng.bounded(n)], s[rng.bounded(n)])
	}
	var m [3]float64
	for i := range m {
		m[i] = medianOf3(s[rng.bounded(n)], s[rng.bounded(n)], s[rng.bounded(n)])
	}
	return medianOf3(m[0], m[1], m[2])
}

func recurseF64(keys []float64, pivot float64, buf *[bufLen64]float64, rng *sfc64, depth int) {
	for {
		if len(keys) <= baseCase64 {
			sortBaseF64(keys)
			return
		}
		if depth <= 0 {
			guardFired()
			heapSort(keys)
			return
		}
		depth--

		bound := partitionF64(keys, pivot, archsimd.BroadcastFloat64x2(pivot), buf)
		left, right := keys[:bound], keys[bound:]

		if len(right) == 0 {
			lo, hi := minMaxF64(keys)
			if lo == hi {
				return
			}
			pivot = lo
			continue
		}

		if len(left) <= len(right) {
			recurseF64(left, choosePivotF64(left, rng), buf, rng, depth)
			keys, pivot = right, choosePivotF64(right, rng)
		} else {
			recurseF64(right, choosePivotF64(right, rng), buf, rng, depth)
			keys, pivot = left, choosePivotF64(left, rng)
		}
	}
}
